language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

notifications:
  email:
    - chris.m.fournier@gmail.com

install:
  - make install_requirements
  - make install

script: make test

# whitelist
branches:
  only:
    - master
    - experimental

after_success:
  - make coveralls

matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"