language: python

python:
  - "2.7"

notifications:
  email:
    - chris.m.fournier@gmail.com

install:
    - pip install -r requirements.txt --use-mirrors

script: make coverage_report

# whitelist
branches:
  only:
    - master
    - experimental

after_success:
  - make coveralls